name: duyurubu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0      # Flutter 3.7 uyumlu
  permission_handler: ^11.0.1           # Android 12+ izinleri uyumlu
  cupertino_icons: ^1.0.8
  provider: ^6.0.5                      # Flutter 3.7 ile uyumlu en g端ncel 6.x s端r端m端
  flutter_localizations:
    sdk: flutter
  translator: ^1.0.3+1
  image_picker: ^1.0.4
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
